name: 'Build'
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - run: npm install

      # Hem Windows (.exe) hem Linux (.AppImage) derlemesi yapar
      - run: npm run build -- --win --linux -p never

      # Oluşan derleme dosyalarını GitHub Actions paneline yükler
      - uses: actions/upload-artifact@v4
        with:
          name: Solar-Tweaks-Executables
          path: |
            dist/*.AppImage
            dist/*.exe
